### ISSUE TITLE
False Positive: can't execute the commands through shell

### ISSUE THREAD

**Issue by MyRootChutiya** [dreadlocked/Drupalgeddon2#39]
well drupalgeddon2.rb said shell is wroted in Root Dir 

Very Good News Everyone! Wrote to the web root! Waayheeeey!!!
--------------------------------------------------------------------------------
[i] Fake shell:   curl 'https://site.com/user/password/s.php' -d 'c=hostname'

but it doesn't execute the command as well as it just hang my terminal 
see the screenshot :(
![screenshot 33 _li](https://user-images.githubusercontent.com/31159899/39450199-1fa30aaa-4ce8-11e8-9832-4a5b27f3221c.jpg)

**Comment by g0tmi1k** [comment]
Is the PHP function disabled?

**Comment by MyRootChutiya** [comment]
you talking about ..

> # Function gen_evil_url <cmd> [shell]
def gen_evil_url(evil, shell=false)
  # PHP function to use (don't forget about disabled functions...)
  phpfunction = $drupalverion.start_with?("8")? "exec" : "passthru"
  phpfunction = "passthru"

  puts "[i] PHP cmd: #{phpfunction}" if shell
  puts "[i] Payload: #{evil}" if not shell

this..?
![screenshot 36](https://user-images.githubusercontent.com/31159899/39513164-122e4f04-4e11-11e8-8d78-2d7c6a565344.png)

still it didn't work
i don't have any idea..help..!!

**Comment by m4lv0id** [comment]
@MyRootChutiya The problem you are facing is most probably due to the PHP function `system()` is disabled on the server-site but you can write files to the web-root, which you could have decoded and check before hand and also I would suggest you to read more on the same. [PHP.INI disable_functions](https://www.cyberciti.biz/faq/linux-unix-apache-lighttpd-phpini-disable-functions/)

<img width="1249" alt="screen shot 2018-05-02 at 10 55 27" src="https://user-images.githubusercontent.com/29372616/39514467-83fd5824-4df7-11e8-9ba8-6a579fdf6155.png">

There are possible ways to bypass these protection, Example : [PHP < 5.6.2 - 'Shellshock' 'disable_functions()' Bypass Command Injection](https://www.exploit-db.com/exploits/35146/) which to work you need to make sure you have a vulnerable bash on machine (Windows servers are not affected) or If I remember correctly you can bypass it via some CGI tricks too.

Off that said, I guess there is nothing wrong with the exploit functionality but then a timeout can be added to the exploit to mitigate the terminal hang you mentioned about. 

P.S - I'm pretty sure that this exploit is for **educational** and **research purposes**. So, do make you are using it in those limits.
